const {readFileSync,writeFileSync}=require('fs')
const first=readFileSync('./content/first.txt','utf8')
const second=readFileSync('./content/Second.txt','utf8')
console.log(first,second)
writeFileSync('./Content/result-sync.txt',`Here is the result: ${first},${second}`,{flag:'a'})